// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Lecturer readonly & record {
    # Staff number of the lecturer
    string staff_number;
    # Office numer of the lecturer
    string office_number;
    # Name of the lecturer
    string staff_name;
    # Title of the lecturer
    string title;
    # Coureses Taken By The lecturer
    string[] courses_taken;
};
table<Lecturer> key(staff_number) lecturer = table [

];
